/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as SmeRouteImport } from './routes/sme'
import { Route as IndexRouteImport } from './routes/index'

const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const SmeRoute = SmeRouteImport.update({
  id: '/sme',
  path: '/sme',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sme': typeof SmeRoute
  '/wallets': typeof WalletsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sme': typeof SmeRoute
  '/wallets': typeof WalletsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sme': typeof SmeRoute
  '/wallets': typeof WalletsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sme' | '/wallets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sme' | '/wallets'
  id: '__root__' | '/' | '/sme' | '/wallets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SmeRoute: typeof SmeRoute
  WalletsRoute: typeof WalletsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sme': {
      id: '/sme'
      path: '/sme'
      fullPath: '/sme'
      preLoaderRoute: typeof SmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SmeRoute: SmeRoute,
  WalletsRoute: WalletsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
