/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletsRouteImport } from './routes/_authenticated/wallets'
import { Route as AuthenticatedSmeRouteImport } from './routes/_authenticated/sme'
import { Route as AuthenticatedMyWalletRouteImport } from './routes/_authenticated/my-wallet'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppWalletRouteImport } from './routes/_authenticated/app/wallet'
import { Route as AuthenticatedAppTransactionsRouteImport } from './routes/_authenticated/app/transactions'
import { Route as AuthenticatedAppRemittanceRouteImport } from './routes/_authenticated/app/remittance'
import { Route as AuthenticatedAppBeneficiariesRouteImport } from './routes/_authenticated/app/beneficiaries'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletsRoute = AuthenticatedWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSmeRoute = AuthenticatedSmeRouteImport.update({
  id: '/sme',
  path: '/sme',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyWalletRoute = AuthenticatedMyWalletRouteImport.update({
  id: '/my-wallet',
  path: '/my-wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppWalletRoute = AuthenticatedAppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppTransactionsRoute =
  AuthenticatedAppTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppRemittanceRoute =
  AuthenticatedAppRemittanceRouteImport.update({
    id: '/remittance',
    path: '/remittance',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppBeneficiariesRoute =
  AuthenticatedAppBeneficiariesRouteImport.update({
    id: '/beneficiaries',
    path: '/beneficiaries',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/my-wallet': typeof AuthenticatedMyWalletRoute
  '/sme': typeof AuthenticatedSmeRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/app/beneficiaries': typeof AuthenticatedAppBeneficiariesRoute
  '/app/remittance': typeof AuthenticatedAppRemittanceRoute
  '/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/app/wallet': typeof AuthenticatedAppWalletRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-wallet': typeof AuthenticatedMyWalletRoute
  '/sme': typeof AuthenticatedSmeRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/app/beneficiaries': typeof AuthenticatedAppBeneficiariesRoute
  '/app/remittance': typeof AuthenticatedAppRemittanceRoute
  '/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/app/wallet': typeof AuthenticatedAppWalletRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/my-wallet': typeof AuthenticatedMyWalletRoute
  '/_authenticated/sme': typeof AuthenticatedSmeRoute
  '/_authenticated/wallets': typeof AuthenticatedWalletsRoute
  '/_authenticated/app/beneficiaries': typeof AuthenticatedAppBeneficiariesRoute
  '/_authenticated/app/remittance': typeof AuthenticatedAppRemittanceRoute
  '/_authenticated/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/_authenticated/app/wallet': typeof AuthenticatedAppWalletRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/my-wallet'
    | '/sme'
    | '/wallets'
    | '/app/beneficiaries'
    | '/app/remittance'
    | '/app/transactions'
    | '/app/wallet'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/my-wallet'
    | '/sme'
    | '/wallets'
    | '/app/beneficiaries'
    | '/app/remittance'
    | '/app/transactions'
    | '/app/wallet'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/my-wallet'
    | '/_authenticated/sme'
    | '/_authenticated/wallets'
    | '/_authenticated/app/beneficiaries'
    | '/_authenticated/app/remittance'
    | '/_authenticated/app/transactions'
    | '/_authenticated/app/wallet'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallets': {
      id: '/_authenticated/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthenticatedWalletsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sme': {
      id: '/_authenticated/sme'
      path: '/sme'
      fullPath: '/sme'
      preLoaderRoute: typeof AuthenticatedSmeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-wallet': {
      id: '/_authenticated/my-wallet'
      path: '/my-wallet'
      fullPath: '/my-wallet'
      preLoaderRoute: typeof AuthenticatedMyWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/wallet': {
      id: '/_authenticated/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AuthenticatedAppWalletRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/transactions': {
      id: '/_authenticated/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AuthenticatedAppTransactionsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/remittance': {
      id: '/_authenticated/app/remittance'
      path: '/remittance'
      fullPath: '/app/remittance'
      preLoaderRoute: typeof AuthenticatedAppRemittanceRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/beneficiaries': {
      id: '/_authenticated/app/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/app/beneficiaries'
      preLoaderRoute: typeof AuthenticatedAppBeneficiariesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppBeneficiariesRoute: typeof AuthenticatedAppBeneficiariesRoute
  AuthenticatedAppRemittanceRoute: typeof AuthenticatedAppRemittanceRoute
  AuthenticatedAppTransactionsRoute: typeof AuthenticatedAppTransactionsRoute
  AuthenticatedAppWalletRoute: typeof AuthenticatedAppWalletRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppBeneficiariesRoute: AuthenticatedAppBeneficiariesRoute,
  AuthenticatedAppRemittanceRoute: AuthenticatedAppRemittanceRoute,
  AuthenticatedAppTransactionsRoute: AuthenticatedAppTransactionsRoute,
  AuthenticatedAppWalletRoute: AuthenticatedAppWalletRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedMyWalletRoute: typeof AuthenticatedMyWalletRoute
  AuthenticatedSmeRoute: typeof AuthenticatedSmeRoute
  AuthenticatedWalletsRoute: typeof AuthenticatedWalletsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedMyWalletRoute: AuthenticatedMyWalletRoute,
  AuthenticatedSmeRoute: AuthenticatedSmeRoute,
  AuthenticatedWalletsRoute: AuthenticatedWalletsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
